'''
Домашнее задание
В файле .py, написать переменные с XPATH,
всех ответов и их вариантов с сайта

https://www.mensa.lu/en/mensa/online-iq-test/online-iq-test.html

xpath_question1_entry = '//input[@name="q1"]'
xpath_question9_radio_b = '//input[@name="q9"][@value="b"]'
# '//input[@name="q9" and @value="b"]'
#//img[@src="/images/site/iq21a.gif"]
Файл .py прислать в MyStat
'''
'''
всех ответов и их вариантов с сайта     
all answers and their options from the site
'''
# Variant-1
xpath_answer_1 = '//input[@name="q1"]'
xpath_answer_2 = '//input[@name="q2"]'
xpath_answer_3 = '//input[@name="q3"]'
xpath_answer_4 = '//input[@name="q4"]'
xpath_answer_5 = '//input[@name="q5"]'
xpath_answer_6 = '//input[@name="q6"]'
xpath_answer_7 = '//input[@name="q7"]'
xpath_answer_8 = '//input[@name="q8"]'
xpath_answer_9_a = '//input[@name="q9"][@value="a"]'
xpath_answer_9_b = '//input[@name="q9"][@value="b"]'
xpath_answer_9_c = '//input[@name="q9"][@value="c"]'
xpath_answer_9_d = '//input[@name="q9"][@value="d"]'
xpath_answer_10_a = '//input[@name="q10"][@value="a"]'
xpath_answer_10_b = '//input[@name="q10"][@value="b"]'
xpath_answer_10_c = '//input[@name="q10"][@value="c"]'
xpath_answer_10_d = '//input[@name="q10"][@value="d"]'
xpath_answer_11_a = '//input[@name="q11"][@value="a"]'
xpath_answer_11_b = '//input[@name="q11"][@value="b"]'
xpath_answer_11_c = '//input[@name="q11"][@value="c"]'
xpath_answer_11_d = '//input[@name="q11"][@value="d"]'
xpath_answer_12_a = '//input[@name="q12"][@value="a"]'
xpath_answer_12_b = '//input[@name="q12"][@value="b"]'
xpath_answer_12_c = '//input[@name="q12"][@value="c"]'
xpath_answer_12_d = '//input[@name="q12"][@value="d"]'
xpath_answer_13_a = '//input[@name="q13"][@value="a"]'
xpath_answer_13_b = '//input[@name="q13"][@value="b"]'
xpath_answer_13_c = '//input[@name="q13"][@value="c"]'
xpath_answer_13_d = '//input[@name="q13"][@value="d"]'
xpath_answer_14_a = '//input[@name="q14"][@value="a"]'
xpath_answer_14_b = '//input[@name="q14"][@value="b"]'
xpath_answer_14_c = '//input[@name="q14"][@value="c"]'
xpath_answer_14_d = '//input[@name="q14"][@value="d"]'
xpath_answer_15_a = '//input[@name="q15"][@value="a"]'
xpath_answer_15_b = '//input[@name="q15"][@value="b"]'
xpath_answer_15_c = '//input[@name="q15"][@value="c"]'
xpath_answer_15_d = '//input[@name="q15"][@value="d"]'
xpath_answer_16_a = '//input[@name="q16"][@value="a"]'
xpath_answer_16_b = '//input[@name="q16"][@value="b"]'
xpath_answer_16_c = '//input[@name="q16"][@value="c"]'
xpath_answer_16_d = '//input[@name="q16"][@value="d"]'
xpath_answer_17_a = '//input[@name="q17"][@value="a"]'
xpath_answer_17_b = '//input[@name="q17"][@value="b"]'
xpath_answer_17_c = '//input[@name="q17"][@value="c"]'
xpath_answer_17_d = '//input[@name="q17"][@value="d"]'
xpath_answer_18_a = '//input[@name="q18"][@value="a"]'
xpath_answer_18_b = '//input[@name="q18"][@value="b"]'
xpath_answer_18_c = '//input[@name="q18"][@value="c"]'
xpath_answer_18_d = '//input[@name="q18"][@value="d"]'
xpath_answer_19_check_a = '//input[@name="q19"][@value="a"]'
xpath_answer_19_check_b = '//input[@name="q19"][@value="b"]'
xpath_answer_19_check_c = '//input[@name="q19"][@value="c"]'
xpath_answer_19_check_d = '//input[@name="q19"][@value="d"]'
xpath_answer_19_check_e = '//input[@name="q19"][@value="e"]'
xpath_answer_20_check_a = '//input[@name="q20"][@value="a"]'
xpath_answer_20_check_b = '//input[@name="q20"][@value="b"]'
xpath_answer_20_check_c = '//input[@name="q20"][@value="c"]'
xpath_answer_20_check_d = '//input[@name="q20"][@value="d"]'
xpath_answer_20_check_e = '//input[@name="q20"][@value="e"]'
xpath_answer_21_check_a = '//input[@name="q21"][@value="a"]'
xpath_answer_21_check_b = '//input[@name="q21"][@value="b"]'
xpath_answer_21_check_c = '//input[@name="q21"][@value="c"]'
xpath_answer_21_check_d = '//input[@name="q21"][@value="d"]'
xpath_answer_21_check_e = '//input[@name="q21"][@value="e"]'
xpath_answer_22_check_a = '//input[@name="q22"][@value="a"]'
xpath_answer_22_check_b = '//input[@name="q22"][@value="b"]'
xpath_answer_22_check_c = '//input[@name="q22"][@value="c"]'
xpath_answer_22_check_d = '//input[@name="q22"][@value="d"]'
xpath_answer_22_check_e = '//input[@name="q22"][@value="e"]'
xpath_answer_23_a = '//input[@name="q23"][@value="a"]'
xpath_answer_23_b = '//input[@name="q23"][@value="b"]'
xpath_answer_23_c = '//input[@name="q23"][@value="c"]'
xpath_answer_23_d = '//input[@name="q23"][@value="d"]'
xpath_answer_24_a = '//input[@name="q24"][@value="a"]'
xpath_answer_24_b = '//input[@name="q24"][@value="b"]'
xpath_answer_24_c = '//input[@name="q24"][@value="c"]'
xpath_answer_24_d = '//input[@name="q24"][@value="d"]'
xpath_answer_25_a = '//input[@name="q25"][@value="a"]'
xpath_answer_25_b = '//input[@name="q25"][@value="b"]'
xpath_answer_25_c = '//input[@name="q25"][@value="c"]'
xpath_answer_25_d = '//input[@name="q25"][@value="d"]'
xpath_answer_26_a = '//input[@name="q26"][@value="a"]'
xpath_answer_26_b = '//input[@name="q26"][@value="b"]'
xpath_answer_26_c = '//input[@name="q26"][@value="c"]'
xpath_answer_26_d = '//input[@name="q26"][@value="d"]'
xpath_answer_27_a = '//input[@name="q27"][@value="a"]'
xpath_answer_27_b = '//input[@name="q27"][@value="b"]'
xpath_answer_27_c = '//input[@name="q27"][@value="c"]'
xpath_answer_27_d = '//input[@name="q27"][@value="d"]'
xpath_answer_28_a = '//input[@name="q28"][@value="a"]'
xpath_answer_28_b = '//input[@name="q28"][@value="b"]'
xpath_answer_28_c = '//input[@name="q28"][@value="c"]'
xpath_answer_28_d = '//input[@name="q28"][@value="d"]'
xpath_answer_29_a = '//input[@name="q29"][@value="a"]'
xpath_answer_29_b = '//input[@name="q29"][@value="b"]'
xpath_answer_29_c = '//input[@name="q29"][@value="c"]'
xpath_answer_29_d = '//input[@name="q29"][@value="d"]'
xpath_answer_30_a = '//input[@name="q30"][@value="a"]'
xpath_answer_30_b = '//input[@name="q30"][@value="b"]'
xpath_answer_30_c = '//input[@name="q30"][@value="c"]'
xpath_answer_30_d = '//input[@name="q30"][@value="d"]'
xpath_answer_31_a = '//input[@name="q31"][@value="a"]'
xpath_answer_31_b = '//input[@name="q31"][@value="b"]'
xpath_answer_31_c = '//input[@name="q31"][@value="c"]'
xpath_answer_31_d = '//input[@name="q31"][@value="d"]'
xpath_answer_32_a = '//input[@name="q32"][@value="a"]'
xpath_answer_32_b = '//input[@name="q32"][@value="b"]'
xpath_answer_32_c = '//input[@name="q32"][@value="c"]'
xpath_answer_32_d = '//input[@name="q32"][@value="d"]'
xpath_answer_33_a = '//input[@name="q33"][@value="a"]'
xpath_answer_33_b = '//input[@name="q33"][@value="b"]'
xpath_answer_33_c = '//input[@name="q33"][@value="c"]'
xpath_answer_33_d = '//input[@name="q33"][@value="d"]'
xpath_finished = '//input[@value="FINISHED"]'
